### ISSUE TITLE
Style todos

### ISSUE THREAD

**Issue by smauch** [Check-den-Fakt/Frontend#10]
## Landing Page: Willkommenstext ändern: 
Die Anzahl an Falschmeldungen zum Coronavirus steigt immer weiter an. Dabei sind diese Nachrichten teilweise so professionell verfälscht, dass die Bewertung des Wahrheitsgehalts nicht sofort erkennbar ist. Das kann zu Unsicherheiten und Fehlverhalten führen – manchmal mit dramatischen Folgen.
—> Lass uns den unbedingt noch mit Christoph gestalten.
zB: “Dabei sind diese Nachrichten teilweise so professionell verfälscht, dass der Wahrheitsgehalt nicht sofort erkennbar ist.

## Landing Page: Worum geht’s hier?
--> Check den Fakt, nicht Check the Fact (bearbeitet) 

## Ist die Nachricht glaubwürdig (…)
nächster Absatz, sodass Satz auf einer Linie

## Landing Page: So prüfst du deine Nachrichten
--> 1. Nachricht hochladen: Chech den Fakt, nicht Check the Fact
--> 2. Ergebnis erhalten: Aufzählungspunkte den Farben anpassen

## Landing Page: Footer
Impressum und Datenschutzerklärung lila

## Goldene Regeln: Fake-News entlarven
--> Coronavirus blau oder lila?

## About us: Unsere Mission
--> “Und dies mit einem …” schlechter Anfang. Müssen wir umgestalten

## Goldene Regeln: 
--> Texte mit Christoph ändern

## About us: Unsere Vision
--> “Denn in Krisenzeiten ist es umso wichtiger, dass die Wahrheit viral geht.”
Satz muss umgestellt werden

**Comment by martl** [comment]
Es wäre praktischer, wenn du kleinere Tickets machst ;) Ich habe jetzt mal die Texte die schon feststehen, geändert (also Check den Fakt statt Check the Fact) und den Absatz bei "Ist ihre Nachricht glaubwürdig" einfügen, ich hoffe es passt so. Wenn du größere Schriften willst, bitte im mit Angabe der Schriftgröße, dann ändere ich gerne. Auf gut Glück macht für mich wenig Sinn, dann muss ich es 10 mal anpassen. Kümmere mich jetzt noch um die Farben der Aufzählungspunkte und Impring/DSVGO
