### ISSUE TITLE
User reliability test 

### ISSUE THREAD

**Issue by frulo** [Check-den-Fakt/Frontend#22]
**Is your feature request related to a problem? Please describe.**
As soon as user can vote/confirm fake news, we have to check the reliability of this reports.

**Describe the solution you'd like**
One possibility: 
- user has to evaluate fake "fake news" and we can estimate the reliability of the user....

**Comment by martl** [comment]
Müsste erstmal im Konzept erarbeitet werden, oder gibt es das dort schon? Siehe Figma... 

https://www.figma.com/file/2HJxHcFdHEVkHYW8NjvqIi/Corona-News-Checker?node-id=55%3A360

**Comment by frulo** [comment]
extension of this requirement https://github.com/Check-den-Fakt/Frontend/issues/6
