### ISSUE TITLE
Find issues with polygons

### ISSUE THREAD

**Issue by smauch** [Check-den-Fakt/Frontend#8]
![image](https://user-images.githubusercontent.com/34418781/77792249-53057e00-7068-11ea-8652-45aacfeeb23d.png)

**Comment by martl** [comment]
Wie produzierst du den Fehler? Ich habe den nicht in meinem Chrome auf Desktop (Mac). Was benutzt du? @smauch

**Comment by martl** [comment]
kann aktuell nicht reproduziert werden. falls es wieder auftaucht bitte wieder öffnen
